### ISSUE TITLE
Program attempts to download uncompressed map from server

### ISSUE THREAD

**Issue by Cyclic3** [M-Reimer/csgo-csmd#1]
When I am in a server and it changes maps, `csgo-csmd` seems to try to download the map without the .bz2 extension from the server. This fails, and I either have to a) manually download it, or b) restart the game and dump a new log.

**Comment by M-Reimer** [comment]
If the server changes maps, it should hang again at downloading (0%). In this case you have to disconnect again, use csgo-csmd and "retry" after that. It can only work this way as the map download could trigger additional downloads which are only added to the log if a "disconnect" is sent.

Did you do it this way? If yes, it would be interesting to know the server IP so I can try that, too.

My version of the script also does not require dumping logs at all if properly set up. It just uses the "console.log" which automatically represents the current console output without dumping anything.

**Comment by Cyclic3** [comment]
I have also adjusted the script to use console.log

It works fine when joining the server fresh in the way you describe, but when the map changes, I hit this issue.

The server in which I encountered this issue is at 185.42.222.131:27015

**Comment by M-Reimer** [comment]
I've tried this server and for me it works without any changes...

I can only guess one case where things may go wrong. If a "map change" somehow works without server reconnect, then the log parser would fail.

But in my test I always was reconnected before the map changed.

Do you use the latest GIT version available here?

Can you share the "console.log" file for a case where the error occurs, so I can run this manually through csgo-csmd?

Edit: I've tagged the current state as "version 1.0.0". So you now may also try with the "latest release".

**Comment by Cyclic3** [comment]
Sorry for the late response. I have been busy over the last few days.

The latest version does not read from console.log. I do have my csgo installation in a non-standard location, but I have updated the config file to reflect this, and it works fine with condump.

here is a condump that causes the issue
https://gist.github.com/Cyclic3/3fb573cb343a249d56998efca08b9b6c

**Comment by M-Reimer** [comment]
I'll have a look at this in detail later. I had a short look over your log, but everything seems to be the way I would expect it. This should work!

Are you absolutely 100% sure that you use *my* **unmodified** version of csgo-csmd? I mean the one from this GIT repo:
https://github.com/M-Reimer/csgo-csmd
Or the release 1.0.0 from here:
https://github.com/M-Reimer/csgo-csmd/releases

I don't support the "original version" (which seems to be no longer maintained).

My version does *not* work with condump!!! ONLY console.log!
The original version did not work with console.log and also failed if more than one server connection was inside the condump log.

**Comment by Cyclic3** [comment]
I am an idiot.

I have read the commit log, and it seems that I have blindly executed the commands in the README, and as such have downloaded the unforked version

I will try YOUR version this evening.

Thanks for the help!

**Comment by Cyclic3** [comment]
Sorry for this =(
